### ISSUE TITLE
Help generating to a file

### ISSUE THREAD

**Issue by tami5** [dlunch/typescript-wasm-bindgen#1]
Hello @dlunch, I was so happy to see this package. I've spent few hours trying to make it work but no luck. Is it possible to provide steps to generating a rust file from d.ts file. It would help out a lot.

Thanks.

**Comment by dlunch** [comment]
Wow, I didn't expect actual user of this library!

I have implemented very little subset of typescript definition, so many `d.ts` file will not work. Could you share some error messages for further investigation? 

Thanks!

**Comment by tami5** [comment]
Actually I'm trying to generate this https://github.com/obsidianmd/obsidian-api/blob/master/obsidian.d.ts 😆 , I cloned the repo, change all reference to this file and tired test, build and no luck. I can't find the generated file. That file contains mostly classes with dependencies between them

**Comment by dlunch** [comment]
`obsidian.d.ts` file has many typescript syntax i didn't implement yet. It won't work with current version of this package.

**Comment by tami5** [comment]
Oh that's unfortunate, no issue. If you need help I'm available at discord  tami5#1560. Thanks
